import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import pg from 'pg';

const { Client } = pg;

function readDatabaseUrl() {
    const envPath = path.resolve('.env.vercel.production');
    const content = fs.readFileSync(envPath, 'utf8');
    const match = content.match(/^DATABASE_URL="([^"]+)"$/m);
    if (!match) {
        throw new Error('No se encontro DATABASE_URL en .env.vercel.production');
    }
    return match[1];
}

const databaseUrl = process.env.DATABASE_URL || readDatabaseUrl();

const schemaSql = `
BEGIN;

DROP TABLE IF EXISTS accesos CASCADE;
DROP TABLE IF EXISTS old_passwords CASCADE;
DROP TABLE IF EXISTS puestos_traducciones CASCADE;
DROP TABLE IF EXISTS puestos CASCADE;
DROP TABLE IF EXISTS naves CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE accesos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  ip VARCHAR(45) NOT NULL,
  user_agent TEXT NOT NULL,
  fecha TIMESTAMP NOT NULL,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('acceso', 'desconexion'))
);

CREATE TABLE old_passwords (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  password VARCHAR(255) NOT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE naves (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20),
  numero VARCHAR(10) NOT NULL
);

CREATE TABLE puestos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caseta CHAR(5) NOT NULL UNIQUE,
  nombre VARCHAR(50) NOT NULL DEFAULT 'Desconocido',
  imagen TEXT,
  contacto VARCHAR(250),
  telefono VARCHAR(15),
  id_nave INTEGER REFERENCES naves(id),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  tipo_unity VARCHAR(30) NOT NULL DEFAULT 'default',
  caseta_padre CHAR(5)
);

CREATE TABLE puestos_traducciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  puesto_id INTEGER NOT NULL REFERENCES puestos(id) ON DELETE CASCADE,
  codigo_idioma VARCHAR(5) NOT NULL,
  nombre_idioma VARCHAR(20) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  descripcion TEXT,
  CONSTRAINT puestos_traducciones_unique UNIQUE (puesto_id, codigo_idioma)
);

INSERT INTO naves (id, tipo, numero) VALUES
(1, 'Nave 1', '1'),
(2, 'Nave 2', '2'),
(3, 'Nave 3', '3'),
(4, 'Nave 4', '4'),
(5, 'Nave 5', '5'),
(6, 'Nave 6', '6'),
(7, 'Nave 7', '7'),
(8, 'Nave 8', '8'),
(9, 'Amea 1', ''),
(10, 'Amea 5', ''),
(11, 'Murallon 1', ''),
(12, 'Murallon 2', '');

INSERT INTO puestos (id, caseta, nombre, imagen, contacto, telefono, id_nave, activo, tipo_unity, caseta_padre) VALUES
(1, 'CE001', 'Bibi Handmades', '', '', '', 9, TRUE, 'handicraft', NULL),
(2, 'CE003', 'Cuarto Pexigo', '', '', '', 9, TRUE, 'handicraft', NULL),
(3, 'NA350', '', '', '', '', 11, TRUE, 'default', 'NA346');

INSERT INTO puestos_traducciones (id, puesto_id, codigo_idioma, nombre_idioma, tipo, descripcion) VALUES
(1, 1, 'es', 'Espanol', 'Artesania', 'Artesania en piel, sello de artesania de Andalucia.'),
(2, 1, 'gl', 'Gallego', 'Artesania', 'Artesania en pel sello de artesania de Andalucia'),
(3, 1, 'en', 'Ingles', 'Handicraft', 'Leather crafts with the Andalusian craftsmanship seal.'),
(4, 1, 'fr', 'Frances', 'Artesania', 'Artisanat en cuir, label d''artisanat d''Andalousie.'),
(5, 2, 'es', 'Espanol', 'Artesania', 'Productos artisticos.'),
(6, 2, 'gl', 'Gallego', 'Artesania', 'Productos artisticos.'),
(7, 2, 'en', 'Ingles', 'Handicraft', 'Artistic products.'),
(8, 2, 'fr', 'Frances', 'Artesania', 'Produits artistiques.'),
(9, 3, 'es', 'Espanol', '', ''),
(10, 3, 'gl', 'Gallego', '', ''),
(11, 3, 'en', 'Ingles', '', ''),
(12, 3, 'fr', 'Frances', '', '');

COMMIT;
`;

const adminHash = '$argon2id$v=19$m=65536,t=3,p=1$cGR5ekIvaFlGV1VVZkxNcg$hBGbbx5/7ZdbqHPva4CEVXHCzKSJFtHhIaCHN8Sd4hI';

const client = new Client({
    connectionString: databaseUrl,
    ssl: { rejectUnauthorized: false },
});

try {
    await client.connect();
    await client.query(schemaSql);

    await client.query(
        `INSERT INTO usuarios (id, login, password)
     VALUES ($1, $2, $3)
     ON CONFLICT (id)
     DO UPDATE SET login = EXCLUDED.login, password = EXCLUDED.password`,
        [1, 'admintest', adminHash]
    );

    console.log('Base inicial cargada en Neon');
    console.log('Usuario: admintest');
    console.log('Password: Admin1234!!Aa');
} finally {
    await client.end();
}
